name: Build samples
on:   
  push:
    branches: [ "main" ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: /
          root_file: [ "*.tex" ]

      - name: Upload PDF file to GitHub Action
        uses: actions/upload-artifact@v3
        with:
          name: Sample resumes
          path: sample.pdf

      - name: Push to another branch
        run: |
          git fetch origin samples:samples
          git checkout samples
          git add *.pdf
          git commit -m 'Updated the samples'
          git push