name: Build samples
on:   
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: sample.tex

      - name: Upload PDF file to GitHub Action
        uses: actions/upload-artifact@v4
        with:
          name: Sample resume
          path: sample.pdf
